name: flutter_application
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_bloc: 8.1.6
  reactive_button: ^0.0.9
  dartz:
  dio:
  logger:
  get_it:
  http: ^1.6.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.2
  fan_carousel_image_slider: ^1.3.0
  chewie: ^1.13.0
  video_player: ^2.10.1
  youtube_player_flutter: ^9.1.3
  toast: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/welcome.png
    - assets/vectors/
